# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 957eb8948e3771e9df945cbe75d8c765ea8c8ebcae5646ffbb879b9bd1d2407eed862c7eca4603db994c71e8b8f35206ada77e641a6b775fa43f0fbfa57b1dc2

test:
  secret_key_base: 8801d0bd929941cc7037b3fa8a1bc1b829409435dd9fddee1b6d56d5c7a62359c18a96366bb831742e0bf71f4dfa49fcfcc3111fc6e43da3b449fe7dd0093b25

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
